language: c

sudo: true

compiler:
  - clang
  - gcc

python:
  - 3.6

install:
  - sudo apt-get install -y libmcrypt-dev

before_script:
  - (mkdir build && cd build && cmake -DBUILD_TESTING=ON ..)

script:
  - (cd build && make && ctest --verbose)
