language: c

dist: trusty
sudo: true

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libmcrypt-dev

before_script:
  - (mkdir build && cd build && cmake -DBUILD_TESTING=ON ..)

script:
  - (cd build && make && make test)
