language: c

sudo: true

compiler:
        - clang
        - gcc

before_install:
        - sudo add-apt-repository universe
        - sudo apt-get update
        - sudo apt-get install libmcrypt-dev

install: 
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      sudo mkdir /usr/local/build_env
      sudo mv cmake /usr/local/build_env
    fi

before_script: (mkdir build && cd build && /usr/local/build_env/cmake/bin/cmake -DWITH_TESTS=1 ..)

script:
        - (cd build && make)
        - (cd build && sh ../run_tests.sh)