language: c

compiler:
        - clang
        - gcc

install: 
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

before_script: (mkdir build && cd build && ${DEPS_DIR}/cmake/bin/cmake -DWITH_TESTS=1 ..)

script:
        - (cd build && make)
        - (cd build && sh ../run_tests.sh)